# Generated by Django 2.2.10 on 2021-11-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0002_auto_20211119_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
